name: Check and Build Elkulator
run-name: CI Build for Linux Elkulator requested by ${{ github.actor }}
on: [push]
jobs:
  build-allegro4-ubuntu2004:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This job running on a ${{ runner.os }}, triggered by ${{ github.event_name }} event."
      - run: echo "Branch is ${{ github.ref }}, repository is ${{ github.repository }}."
      - name: Install required apt files
        run: |
         sudo apt-get update
         sudo apt-get install -y automake liballegro4-dev zlib1g-dev libalut-dev libopenal-dev cppcheck
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Configure
        run: ./scripts/autoconfigure.sh
      - name: Check source (cppcheck)
        run: cppcheck .
      - name: Build source
        run: make elkulator
      - run: echo "Job Complete.  Status job ${{ job.status }}."

  build-allegro4-ubuntu2204:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "This job running on a ${{ runner.os }}, triggered by ${{ github.event_name }} event."
      - run: echo "Branch is ${{ github.ref }}, repository is ${{ github.repository }}."
      - name: Install required apt files
        run: |
         sudo apt-get update
         sudo apt-get install -y automake liballegro4-dev zlib1g-dev libalut-dev libopenal-dev cppcheck
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Configure
        run: ./scripts/autoconfigure.sh
      - name: Check source (cppcheck)
        run: cppcheck .
      - name: Build source
        run: make elkulator
      - run: echo "Job Complete.  Status job ${{ job.status }}."

  build-allegro4-ubuntu2404:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "This job running on a ${{ runner.os }}, triggered by ${{ github.event_name }} event."
      - run: echo "Branch is ${{ github.ref }}, repository is ${{ github.repository }}."
      - name: Install required apt files
        run: |
         sudo apt-get update
         sudo apt-get install -y automake liballegro4-dev zlib1g-dev libalut-dev libopenal-dev cppcheck
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Configure
        run: ./scripts/autoconfigure.sh
      - name: Check source (cppcheck)
        run: cppcheck .
      - name: Build source
        run: make elkulator
      - run: echo "Job Complete.  Status job ${{ job.status }}."

  build-allegro5-ubuntu2004:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This job running on a ${{ runner.os }}, triggered by ${{ github.event_name }} event."
      - run: echo "Branch is ${{ github.ref }}, repository is ${{ github.repository }}."
      - name: Install required apt files
        run: |
         sudo add-apt-repository ppa:allegro/5.2
         sudo apt-get update
         sudo apt-get install -y automake liballegro5-dev zlib1g-dev libalut-dev libopenal-dev cppcheck
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure
        run: ./scripts/autoconfigure.sh --enable-allegro5
      - name: Check source (cppcheck)
        run: cppcheck .
      - name: Build source
        run: make elkulator
      - run: echo "Job Complete.  Status job ${{ job.status }}."

  build-allegro5-ubuntu2204:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "This job running on a ${{ runner.os }}, triggered by ${{ github.event_name }} event."
      - run: echo "Branch is ${{ github.ref }}, repository is ${{ github.repository }}."
      - name: Install required apt files
        run: |
         sudo add-apt-repository ppa:allegro/5.2
         sudo apt-get update
         sudo apt-get install -y automake liballegro5-dev zlib1g-dev libalut-dev libopenal-dev cppcheck
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure
        run: ./scripts/autoconfigure.sh --enable-allegro5
      - name: Check source (cppcheck)
        run: cppcheck .
      - name: Build source
        run: make elkulator
      - run: echo "Job Complete.  Status job ${{ job.status }}."

  build-allegro5-ubuntu2404:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "This job running on a ${{ runner.os }}, triggered by ${{ github.event_name }} event."
      - run: echo "Branch is ${{ github.ref }}, repository is ${{ github.repository }}."
      - name: Install required apt files
        run: |
         sudo apt-get update
         sudo apt-get install -y automake liballegro5-dev zlib1g-dev libalut-dev libopenal-dev cppcheck
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure
        run: ./scripts/autoconfigure.sh --enable-allegro5
      - name: Check source (cppcheck)
        run: cppcheck .
      - name: Build source
        run: make elkulator
      - run: echo "Job Complete.  Status job ${{ job.status }}."

  build-allegro5-win-msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-allegro make libtool automake autoconf mingw-w64-ucrt-x86_64-freealut
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: CI-Build
        run:  ./scripts/autoconfigure.sh --enable-allegro5
