name: GitHub Actions Demo
run-name: CI Build for Linux Elkulator requested by ${{ github.actor }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job running on a ${{ runner.os }}, triggered by ${{ github.event_name }} event."
      - run: echo "Branch is ${{ github.ref }}, repository is ${{ github.repository }}."
      - name: Install required apt files
        run: |
         sudo apt-get update
         sudo apt-get install -y automake liballegro4-dev zlib1g-dev libalut-dev libopenal-dev cppcheck
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Configure
        run: ./autoconfigure.sh
      - name: Check source (cppcheck)
        run: cppcheck .
      - name: Build source
        run: make
      - run: echo "Job Complete.  Status job ${{ job.status }}."
